server:
  # 设置端口号
  port: 9091

# spring配置
spring:
  # jackson 配置
  jackson:
    # JSON日期格式化
    date-format: yyyy-MM-dd
    # JSON日期格式化设置时区为上海
    time-zone: Asia/Shanghai

  servlet:
    multipart:
      max-file-size: 2MB

  # mvc 配置
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss

  # 配置文件
  profiles:
    active: dev

# mybatis配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: top.zhanglingxi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis-config.xml

# 配置日志
logging:
  # 字符集
  charset:
    # 控制台字符集
    console: utf-8
    # 文件字符集
    file: UTF-8
  # 日志文件
  file:
    # 文件名
    name: logging.log

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 3
    # 密码锁定时间（默认10分钟）
    lockTime: 1